# Generated by Django 2.1.2 on 2018-11-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_NO', models.IntegerField()),
                ('E_NAME', models.CharField(max_length=64)),
                ('E_SAL', models.FloatField()),
                ('E_ADDRESS', models.CharField(max_length=64)),
            ],
        ),
    ]
